import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { sha256 } from '../src/core/completeness.js';

const root = resolve(import.meta.dirname, '..');
const snapshot = JSON.parse(await readFile(resolve(root, 'web/data/latest.json'), 'utf8'));
const outcomes = JSON.parse(await readFile(resolve(root, 'web/data/outcomes.json'), 'utf8'));
const latestOffline = await readFile(resolve(root, 'web/data/latest.js'), 'utf8');
const outcomesOffline = await readFile(resolve(root, 'web/data/outcomes.js'), 'utf8');
const errors = [];
if (!['COMPLETE', 'PARTIAL', 'BLOCKED', 'STALE'].includes(snapshot.dataStatus)) errors.push('無效 dataStatus');
if (['BLOCKED', 'STALE'].includes(snapshot.dataStatus) && snapshot.potentialStocks?.length) errors.push('核心資料不可用仍產生排行榜');
if ((snapshot.potentialStocks?.length || 0) > 20) errors.push('候選超過20檔');
if (!['VERIFIED', 'PROVISIONAL', 'UNAVAILABLE'].includes(snapshot.candidateStatus)) errors.push('無效 candidateStatus');
if ((snapshot.potentialStocks || []).some(row => row.score < 50 || !['A', 'B', 'C'].includes(row.grade))) errors.push('排行榜含未達門檻項目');
const payload = structuredClone(snapshot);
delete payload.manifest;
if (snapshot.manifest?.payloadSha256 !== sha256(payload)) errors.push('snapshot雜湊不符');
if (!latestOffline.startsWith('globalThis.__CHIP_LOCK_SNAPSHOT__ = ')) errors.push('缺少離線選股資料包');
if (!outcomesOffline.startsWith('globalThis.__CHIP_LOCK_OUTCOMES__ = ')) errors.push('缺少離線觀察資料包');
if (errors.length) throw new Error(errors.join('；'));
console.log(JSON.stringify({ valid: true, dataStatus: snapshot.dataStatus, candidateStatus: snapshot.candidateStatus, candidates: snapshot.potentialStocks?.length || 0, observations: outcomes.summary?.total || 0 }));
